name: GitHub Actions Demo
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          key: ${{ secrets.FTP_KEY }}
          port: ${{ secrets.FTP_PORT }}
          
      - name: Change current working directory
        run: cd ${{ secrets.UPLOAD_DIR }}
        
      - name: Get latest version
        run: git pull
        
      - name: Restart service
        run: sudo service dicykenny restart
